# Generated by Django 3.2.8 on 2021-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrytable',
            name='group',
            field=models.CharField(choices=[('+', 'income'), ('-', 'expenditrue')], max_length=1),
        ),
    ]
